# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7997312104fe8d002e1aaeeeea7e08bdf028403f4651e424825e659d65355725f6f3a8891d2758f10d60610ef37eaa651ef0e1ba343db6309c92fda716094e6

test:
  secret_key_base: 40de56c7be1da6cc4a9d5f2ad446876814f87f52ae32ead698d68463ee05ffd20fab1cce53260d34ce8686d0ef7e47a79d7c72be4305b39eb55ed376bac7a77d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
